version: '3.8'
services:

  entrypoint:
    build: ./entrypoint_service
    ports:
      - "${ENTRYPOINT_SVC_PORT}:5000"
    networks:
      - microservices_network
    env_file:
      - common.env
    environment:
      - FLASK_RUN_PORT=5000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:${COLLECTOR_GRPC_PORT}

  service_a:
    build: ./service_a
    ports:
      - "${SVC_A_PORT}:5000"
    networks:
      - microservices_network
    env_file:
      - common.env
    environment:
      - FLASK_RUN_PORT=5001

  service_b:
    build: ./service_b
    ports:
      - "${SVC_B_PORT}:5000"
    networks:
      - microservices_network
    env_file:
      - common.env
    environment:
      - FLASK_RUN_PORT=5002

  collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "${COLLECTOR_GRPC_PORT}:4317"
      - "${COLLECTOR_HTTP_PORT}:4318"
    networks:
      - microservices_network
    env_file:
      - common.env
    volumes:
      - ./otel_collector/collector-config.yml:/etc/collector-config.yml
    command: ["--config", "/etc/collector-config.yml"]


networks:
  microservices_network:
    driver: bridge
